spring:
  application:
    name: rabbitmq

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

  queue:
    name: rabbitmq
    json:
      name: rabbitmq_json
  exchange:
    name: rabbitmq_exchange
  routing:
    name: rabbitmq_routing_key
    json:
      name: rabbitmq_routing_json_key
